zalando/spring-cloud-config-aws-kms

.gitignore, .travis.yml, README.md, pom.xml, src/main/java/de/zalando/spring/cloud/config/aws/kms/KmsTextEncryptor.java, src/test/java/de/zalando/spring/cloud/config/aws/kms/KmsTextEncryptorTest.java
add .travis.yml with matrix build on different jdks 7 and 8, ignore
eclipse generated files
=> fix Base64 usage, update to latest spring-boot version (1.2.3.RELEASE),

pom.xml, src/test/java/de/zalando/spring/cloud/config/aws/kms/DisabledKmsEncryptionIntegrationConfigurationTest.java, src/test/java/de/zalando/spring/cloud/config/aws/kms/KmsEncryptionIntegrationConfigurationTest.java, src/test/java/de/zalando/spring/cloud/config/aws/kms/MockAwsKmsConfig.java, src/test/java/de/zalando/spring/cloud/config/aws/kms/NoKmsEncryptionIntegrationConfigurationTest.java
fixes #5 
Upgrade to Spring Boot 1.4 + Spring Cloud Brixton.SR4
=> Upgrade deps

README.md
Add JavaDoc, Maven and License badges to the readme.
=> Should add JavaDoc, Maven and License badges

encryption-cli/pom.xml, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/EncryptionCLI.java, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/TestApplication.java, pom.xml
* spring boot 1.5.1
* spring cloud Camden.SR5
* aws-java-sdk-kms dependency version is now  managed by Spring Cloud
=> upgrade dependencies

.travis.yml, encryption-cli/pom.xml, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/EncryptionCLI.java, pom.xml
Releases the library in version 1.7 and updates the CLI to use the new versions.
=> Release 1.7

CONTRIBUTING.md, MAINTAINERS, README.md, SECURITY.md
* add CONTRIBUTING.md - fixes #19
* add SECURITY.md - fixes #22
=> make this repository compliant to Zalando OSS guidelines

README.md, encryption-cli/README.md, encryption-cli/pom.xml, encryption-cli/run.sh, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/DecryptProperties.java, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/EncryptProperties.java, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/EncryptionCLI.java, encryption-cli/src/main/java/de/zalando/spring/cloud/config/aws/kms/test/TestApplication.java, encryption-cli/src/main/resources/logback.xml, pom.xml, src/main/java/de/zalando/spring/cloud/config/aws/kms/KmsEncryptionConfiguration.java, src/main/java/de/zalando/spring/cloud/config/aws/kms/KmsProperties.java, src/main/java/de/zalando/spring/cloud/config/aws/kms/KmsTextEncryptor.java, src/test/resources/bootstrap-encryption.yml, src/test/resources/bootstrap-noEncryption.yml
Fixes #30 and changes README accordingly, which fixes #29
=> remove Spring Cloud AWS Autoconfigure region handling

pom.xml
Upgrade spring-cloud to Edgware.SR3
=> Upgrade spring-cloud to Edgware.SR3

README.md, encryption-cli/pom.xml, encryption-cli/src/main/resources/logback.xml, pom.xml, src/main/java/de/zalando/spring/cloud/config/aws/kms/KmsTextEncryptor.java, src/test/java/de/zalando/spring/cloud/config/aws/kms/MockAwsKmsConfig.java
Upgrade Spring Cloud to "Finchley" release train, which includes Spring Boot 2.0.
Fixes #33
=> Spring boot 2.0

encryption-cli/pom.xml, pom.xml
=> Release 3.1

encryption-cli/pom.xml, pom.xml
=> Release 3.2

encryption-cli/pom.xml, pom.xml
=> Release 2.2

encryption-cli/pom.xml, pom.xml, src/test/java/de/zalando/spring/cloud/config/aws/kms/KmsTextEncryptorTest.java
Upgrade dependencies and fix deprecation warnings
=> Upgrade to Spring Cloud Greenwich

MAINTAINERS, README.md, pom.xml
- new maintainers Felix and Michele
- small readme improvements
=> added new maintainers and updated readme

encryption-cli/pom.xml, pom.xml
release version 4.0 and update encryption CLI
=> Release 4.0

encryption-cli/pom.xml, pom.xml
=> Release 4.1

.travis.yml, pom.xml
upgrade spring cloud to finchley.sr4
=> upgrade spring cloud to finchley.sr4

.travis.yml, pom.xml
upgrade spring cloud to edgware.sr6
=> upgrade spring cloud to edgware.sr6

pom.xml
=> Release 2.3

pom.xml
=> Perform release 3.3

encryption-cli/pom.xml, pom.xml
=> Perform release 4.3

pom.xml
upgrade spring cloud to Greenwich.SR4
=> upgrade spring cloud to Greenwich.SR4

README.md, pom.xml
upgrade spring cloud to Hoxton + switch to new major version 5
=> upgrade spring cloud to Hoxton

pom.xml
=> release-4.4

encryption-cli/pom.xml, pom.xml
=> Release 5.0

pom.xml
- bump dependencies
- release version 4.5
=> Release 4.5

pom.xml, spring-cloud-config-aws-kms-coverage/pom.xml, spring-cloud-config-aws-kms-encryption-cli/pom.xml, spring-cloud-config-aws-kms-tests/pom.xml, spring-cloud-config-aws-kms-tests/spring-cloud-config-aws-kms-integration-test-1/pom.xml, spring-cloud-config-aws-kms-tests/spring-cloud-config-aws-kms-integration-test-2/pom.xml, spring-cloud-config-aws-kms-tests/spring-cloud-config-aws-kms-test-support/pom.xml, spring-cloud-config-aws-kms/pom.xml
=> Release 5.1

encryption-cli/pom.xml, library/src/test/java/de/zalando/spring/cloud/config/aws/kms/EncryptedTokenTest.java, library/src/test/java/de/zalando/spring/cloud/config/aws/kms/KmsTextEncryptorTest.java, pom.xml, tests/integration-test-3/src/test/java/de/zalando/spring/cloud/config/aws/kms/it/ConfigServerTest.java, tests/pom.xml
Hi friends from Zalando, this is @rogervinas and @daniel-dios from @AdevintaSpain
Thank you for this amazing library, we are using it a lot! 🤓❤️
This PR fixes #109
Actually, we fixed it live on Twitch: https://www.twitch.tv/videos/1013178964
Cheers!
=> Upgrade to Spring Cloud 2020.0.2 Ilford

.github/workflows/maven.yml
Build the project with Github Actions.
=> Build with GitHub actions

.github/workflows/maven-build.yml, README.md, pom.xml, zalando-cloud-aws-autoconfigure/pom.xml, zalando-cloud-aws-kms/README.md, zalando-cloud-aws-kms/pom.xml, zalando-cloud-aws-samples/zalando-cloud-aws-kms-sample/README.md, zalando-cloud-aws-samples/zalando-cloud-aws-kms-sample/pom.xml, zalando-cloud-aws-starters/zalando-cloud-aws-starter-kms/pom.xml
- Improved usability with the starter as the only required dependency - see sample project
- Bumped dependency versions up
- Improvements to README.md (Fixed build badge, removed jacoco invalid references, etc)
- Renamed build Github workflow to simple `Build`
=> improved usability with the starter as the only required dependency

README.md, pom.xml, zalando-cloud-aws-autoconfigure/pom.xml, zalando-cloud-aws-kms/pom.xml, zalando-cloud-aws-samples/zalando-cloud-aws-kms-sample/pom.xml, zalando-cloud-aws-starters/zalando-cloud-aws-starter-kms/pom.xml
Upgrade library to version 3.3
=> release version 3.3
